networks:
  mysql:
    driver: bridge

services:
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local