services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: blog-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=blogdb
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: